import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cookies } from "next/headers";
import { redirect } from "next/navigation";
import ToastProvider from "@/context/toast-context";
import { isAuthTokenValid } from "@/utils/jwt";
import "@/app/globals.css";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const cookieStore = await cookies();
  const token = cookieStore.get("token")?.value;

  if (token) {
    const isValid = isAuthTokenValid(token);
    if (isValid) {
      redirect("/dashboard");
    }
  }

  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased w-dvw h-dvh max-h-dvh max-w-dvw text-slate-900`}
      >
        <ToastProvider>{children}</ToastProvider>
      </body>
    </html>
  );
}
