import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cookies } from "next/headers";
import { redirect } from "next/navigation";
import ToastProvider from "@/context/toast-context";
import "@/app/globals.css";
import NavBar from "@/components/nav-bar";
import { isAuthTokenValid } from "@/utils/jwt";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function DashboardLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const cookieStore = await cookies();
  const token = cookieStore.get("token")?.value;

  if (!token) {
    console.error("Authentication token not found. Redirecting to /login");
    redirect("/login");
  }

  const isTokenValid = isAuthTokenValid(token);
  if (!isTokenValid) {
    redirect("/login");
  }

  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased min-w-dvw min-h-dvh text-slate-900 bg-slate-100`}
      >
        <ToastProvider>
          <NavBar />
          <main className="min-h-[calc(100dvh-52px-28px)]">{children}</main>
          <footer>
            <p className="side-px py-1 text-sm text-slate-400 text-center font-light">
              &copy; Designed & developed by Vaibhav Jaiswar
            </p>
          </footer>
          <div id="dialog-container"></div>
          <div id="popup-container"></div>
        </ToastProvider>
      </body>
    </html>
  );
}
