import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import { cookies } from "next/headers";
import { redirect } from "next/navigation";
import jwt from "jsonwebtoken";
import ToastProvider from "@/context/toast-context";
import "@/app/globals.css";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function DashboardLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const cookieStore = await cookies();
  const token = cookieStore.get("token")?.value;

  if (!token) {
    redirect("/login");
  }

  try {
    jwt.verify(token, process.env.JWT_SECRET!);
  } catch (error) {
    redirect("/login");
  }

  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased w-dvw h-dvh max-h-dvh max-w-dvw text-slate-900 bg-slate-100`}
      >
        <ToastProvider>
          <header className="sticky top-0 shadow-lg">
            <nav className="side-px  py-3 text-slate-100 bg-slate-800">
              <Link
                href="/dashboard"
                className="text-lg text-slate-100! no-underline!"
              >
                Task<strong>Flow</strong>
              </Link>
            </nav>
          </header>
          <main className="min-h-dvh">{children}</main>
          <footer>
            <p className="side-px py-1 text-sm text-slate-400 text-center font-light">
              &copy; Designed & developed by Vaibhav Jaiswar
            </p>
          </footer>
        </ToastProvider>
      </body>
    </html>
  );
}
